<?php

defined('BASEPATH') OR exit('No direct script access allowed');

// This can be removed if you use __autoload() in config.php OR use Modular Extensions
/** @noinspection PhpIncludeInspection */
//To Solve File REST_Controller not found


/**
 * This is an example of a few basic user interaction methods you could use
 * all done with a hardcoded array
 *
 * @package         CodeIgniter
 * @subpackage      Rest Server
 * @category        Controller
 * @author          Phil Sturgeon, Chris Kacerguis
 * @license         MIT
 * @link            https://github.com/chriskacerguis/codeigniter-restserver
 */
use chriskacerguis\RestServer\RestController;
class Tambah extends RESTController
{

    /**
     * Get All Data from this method.
     *
     * @return Response
     */
    public function __construct()
    {
        parent::__construct();
        $this->load->database();
        $this->load->model('Penjualan_Model');
    }

    /**
     * Get All Data from this method.
     *
     * @return Response
     */
   
    // public function index_get()
    // {

    //     $this->load->model('Datamenu_Model', 'ikhi');

    //     $id_menu = $this->get('id_menu');

    //     $data['datamenu'] = $this->ikhi->Datamenuwhere($id_menu);
        
    //     $this->response($data, REST_Controller::HTTP_OK);
    //     // if (!empty($id)) {
    //     //     $data = $this->db->get_where("menu", ['id_menu' => $id])->row_array();
    //     // } else {
    //     //     $data = $this->db->get("menu")->result();
    //     // }

    //     // $this->response($data, REST_Controller::HTTP_OK);
    // }
        // if (!empty($id)) {
    public function index_post()
    {
        // $data = [
        //     'id_trx' => $this->post('id_trx'), // Automatically generated by the model
        //     'id_menu' => $this->post('id_menu'),
        //     'harga' => $this->post('harga'),
        //     'jumlah' => $this->post('jumlah'),
        //     'diskonmenu' => $this->post('diskonmenu'),
        //     'totalbayar' => $this->post('totalbayar')
            
        // ];
        $data1 = file_get_contents('php://input');
        $datas = json_decode($data1,true);

        $data=$datas['data_menu'];
        $i=0;
        $row2=$datas['datao'];
        $id_trx=0;
        $totalbayar=0;
        $kasir_user=0;
        foreach($row2 as $row1){
            $id_trx=$row1['id_trx'];
            $totalbayar=$row1['totalbayar'];
            $kasir_user=$row1['kasir_user'];
        }

        //$this->Penjualan_Model->Simpanbanyak($data);
        foreach ($data as $rows) {
            unset ($data[$i]['namamenu']);
            $i++;
        }
        
        // $this->response($datas,200s);
       // var_dump($data);

        if($this->Penjualan_Model->Simpanbanyak($data)>0 && $this->Penjualan_Model->aksitambahtrx($id_trx,$totalbayar,$kasir_user)>0 ){
            $this->response([
                'status' => true,
                'message'=> 'berhasilditambahkan'
            ],200);
         }
    }
    /**
     * Get All Data from this method.
     *
     * 
     */
}
